#!/usr/bin/env python
# coding: utf-8


#needed for network accessing
import socket
#needed to take arguments
import sys

#default port
PORT = 27993
#variables to keep track of position in arguments
pflag = False
argno = 0
for arg in sys.argv:
    #keep track of if last argument was -p
    if arg == '-p':
        pflag = True
    elif pflag:
        PORT = int(arg)
        pflag = False
    else:
        if (argno == 1):
            HOST = arg
        if (argno == 2):
            ID_NO = arg
        argno += 1


#set up socket s
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
#connect to server
s.connect((HOST, PORT))
s.sendall(b'cs3700fall2020 HELLO ' + ID_NO.encode('utf-8') + b'\n')
response = s.recv(8192).decode('utf-8')
#do as many FINDs as requested
while (response.split()[1] == 'FIND'):
    #make sure the response is formatted correctly
    if (len(response.split()) != 4):
        raise Exception("Unexpected number of arguments")
    ch = response.split()[2]
    search = response.split()[3]
    numoccurences = search.count(ch)
    message = 'cs3700fall2020 COUNT ' + str(numoccurences) + '\n'
    s.sendall(message.encode('utf-8'))
    response = s.recv(8192).decode('utf-8')

#make sure the first non-FIND message is a BYE message
if response.split()[1] == 'BYE':
    print(response.split()[2])
else:
    raise Exception("Unexpected message type after find messages.")
    
#close connection
s.close()    
